// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlmzzrP5-jwWA3T93VW-eYfyvUL6-vFUc',
    appId: '1:1002344068231:web:9f8c04900200b1a1b27422',
    messagingSenderId: '1002344068231',
    projectId: 'synora-9c49e',
    authDomain: 'synora-9c49e.firebaseapp.com',
    storageBucket: 'synora-9c49e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2zGldBWbU3w2R1SAHFckm4wOFRPgjFb0',
    appId: '1:1002344068231:android:aca144b275f59d0cb27422',
    messagingSenderId: '1002344068231',
    projectId: 'synora-9c49e',
    storageBucket: 'synora-9c49e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArr-SojePxAVGpNv25TWsKjWLFrJ4zLwo',
    appId: '1:1002344068231:ios:f93ba6529b181e62b27422',
    messagingSenderId: '1002344068231',
    projectId: 'synora-9c49e',
    storageBucket: 'synora-9c49e.firebasestorage.app',
    iosBundleId: 'com.synora.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArr-SojePxAVGpNv25TWsKjWLFrJ4zLwo',
    appId: '1:1002344068231:ios:f93ba6529b181e62b27422',
    messagingSenderId: '1002344068231',
    projectId: 'synora-9c49e',
    storageBucket: 'synora-9c49e.firebasestorage.app',
    iosBundleId: 'com.synora.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlmzzrP5-jwWA3T93VW-eYfyvUL6-vFUc',
    appId: '1:1002344068231:web:a53ccf579b8960b0b27422',
    messagingSenderId: '1002344068231',
    projectId: 'synora-9c49e',
    authDomain: 'synora-9c49e.firebaseapp.com',
    storageBucket: 'synora-9c49e.firebasestorage.app',
  );
}
